Repository onflow/vscode-cadence, pull requests merged in 2023-01, with the labels that each got.

#203 Add Windows CI
  .github/workflows/ci.yml
  package.json
Labels: Improvement

#209 Update required Flow CLI version to v0.43.1
  extension/src/dependency-installer/installers/flow-cli-installer.ts
Labels: Bugfix, Improvement

#207 Add installer popups
  extension/src/dependency-installer/installer.ts
  extension/src/dependency-installer/installers/flow-cli-installer.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: Feedback, Improvement

#213 Update flow cli install scripts
  extension/src/dependency-installer/installers/flow-cli-installer.ts
Labels: Bugfix

#214 Check for latest flow-cli version
  extension/src/dependency-installer/installers/flow-cli-installer.ts
  extension/src/dependency-installer/installers/version-parsers.ts
  package-lock.json
  package.json
Labels: Feedback, Feature

#220 Enable LS to wait for flow-cli update
  extension/src/emulator/server/language-server.ts
  package-lock.json
  package.json
Labels: Improvement

#223 Update readme
  README.md
  docs/code_gen.gif
  docs/deploy_contracts.gif
  docs/overview.md
Labels: Improvement, Documentation

#222 Configure Dependabot
  .github/dependabot.yml
Labels: Feedback, Improvement

#235 Add missing configuration for access check mode
  extension/src/emulator/server/language-server.ts
Labels: Bugfix

#219 Reload flow configuration when changed
  extension/src/emulator/local/config.ts
  extension/src/emulator/server/language-server.ts
Labels: Improvement

#240 Update required flow-cli version
  extension/src/dependency-installer/installers/flow-cli-installer.ts
  package.json
Labels: Improvement

#243 Refactor emulator integration
  .github/workflows/ci.yml
  README.md
  extension/index.d.ts
  extension/src/dependency-installer/dependency-installer.ts
  extension/src/emulator/emulator-controller.ts
  extension/src/emulator/server/language-server.ts
  extension/test/e2e/0-init.test.ts
  extension/test/e2e/1-switch-accounts.test.ts
  extension/test/e2e/2-deploy-contract.test.ts
  extension/test/e2e/3-send-script.test.ts
  extension/test/e2e/4-send-transaction.test.ts
  extension/test/e2e/cypress-helpers.ts
  extension/test/fixtures/workspace/NonFungibleToken.cdc
  package-lock.json
  package.json
Labels: Feedback, Improvement

#246 Update version to v1.1.0
  extension/src/dependency-installer/installers/flow-cli-installer.ts
  package.json
Labels: Improvement
