Repository onflow/vscode-cadence, pull requests merged in 2023-02, with the labels that each got.

#259 Emulator location detection
  extension/index.d.ts
  extension/src/emulator/local/emulatorScanner.ts
  extension/src/emulator/local/flowConfig.ts
  extension/src/emulator/server/language-server.ts
  package-lock.json
  package.json
Labels: Feedback, Improvement, Feature

#238 Support for new emulator debugger
  extension/src/main.ts
  package.json
Labels: Feature

#265 Release v1.2.0
  README.md
  compile-install.sh
  extension/src/dependency-installer/installers/flow-cli-installer.ts
  package-lock.json
  package.json
Labels: Improvement

#272 Refactor testing framework
  .github/dependabot.yml
  .github/workflows/ci.yml
  extension/index.d.ts
  extension/src/dependency-installer/dependency-installer.ts
  extension/src/dependency-installer/installers/flow-cli-installer.ts
  extension/src/emulator/emulator-controller.ts
  extension/src/emulator/local/emulatorScanner.ts
  extension/src/emulator/local/flowConfig.ts
  extension/src/emulator/server/language-server.ts
  extension/src/extension.ts
  extension/src/main.ts
  extension/src/settings/settings.ts
  extension/src/telemetry/mixpanel-wrapper.ts
  extension/test/e2e/0-init.test.ts
  extension/test/e2e/1-switch-accounts.test.ts
  extension/test/e2e/2-deploy-contract.test.ts
  extension/test/e2e/3-send-script.test.ts
  extension/test/e2e/4-send-transaction.test.ts
  extension/test/e2e/cypress-helpers.ts
  extension/test/index.ts
  extension/test/integration/extension.integration.test.ts
  extension/test/mock/mockSettings.ts
  extension/test/run-tests.ts
  extension/test/unit/account.unit.test.ts
  extension/test/unit/parser.unit.test.ts
  extension/test/utils.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: Technical Debt, Improvement
